use sqlx::PgPool;

pub async fn reset_tables(pool: &PgPool) {
    sqlx::query(
        r#"
        TRUNCATE
          "LiteLLM_AuditLogsTable",
          "LiteLLM_CloudEventReceiptsTable",
          "LiteLLM_ExternalIdentityMappingsTable",
          "LiteLLM_McpInvocationGrantsTable",
          "LiteLLM_ManagedArtifactsTable",
          "LiteLLM_WebSessionsTable",
          "LiteLLM_AgentGroupGrantsTable",
          "LiteLLM_GroupMembersTable",
          "LiteLLM_GroupsTable",
          "LiteLLM_AgentGrantsTable",
          "LiteLLM_GatewayApiKeysTable",
          "LiteLLM_UsersTable",
          "LiteLLM_AgentEvalRunsTable",
          "LiteLLM_ManagedAgentRevisionsTable",
          "LiteLLM_CredentialsTable",
          "LiteLLM_ManagedAgentInboxItemsTable",
          "LiteLLM_ManagedAgentRoutinesTable",
          "LiteLLM_ManagedAgentRunsTable",
          "LiteLLM_ManagedAgentFilesTable",
          "LiteLLM_ManagedAgentMemoriesTable",
          "LiteLLM_ManagedAgentsTable",
          "LiteLLM_ManagedAgentSessionsTable",
          "LiteLLM_ManagedAgentSkillsTable",
          "LiteLLM_ManagedAgentRulesTable",
          "LiteLLM_GatewaySettingsTable",
          "LiteLLM_SavedAgentsTable"
        CASCADE
        "#,
    )
    .execute(pool)
    .await
    .unwrap();
}
